server:
  port: 8080
lxt:
  server: http://localhost:${server.port}
# 文件上传相关配置
file:
  path:
    upload: /www/wwwroot/ueditor/  #文件上传存储位置，不存在会自动创建
    prefix: /filePrefix/  #必须 / 结尾
spring:
  thymeleaf:
    prefix: classpath:/templates/
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.120.130:3306/recover
    username: recover
    password: 123456
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  main:
    allow-circular-references: true
mybatis:
  mapper-locations: classpath:com/mapper/*.xml
  type-aliases-package: com.example.recoverbysporting.entity
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
